# Generated by Django 2.2.5 on 2019-09-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moma_id', models.IntegerField()),
                ('moma_number', models.CharField(max_length=50)),
                ('moma_url', models.URLField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200, null=True)),
                ('moma_url', models.URLField()),
                ('suffix', models.CharField(max_length=25, null=True)),
                ('token', models.CharField(max_length=200)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Exhibition')),
            ],
        ),
    ]
