# Generated by Django 2.2.5 on 2019-09-19 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Exhibition')),
            ],
        ),
    ]
