# Generated by Django 2.2.5 on 2019-09-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='display_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='moma_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='moma_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='moma_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
