# Generated by Django 2.2.5 on 2019-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_auto_20190921_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='exhibition',
        ),
        migrations.AddField(
            model_name='artist',
            name='exhibition',
            field=models.ManyToManyField(to='curator.Exhibition'),
        ),
    ]
